#!/bin/bash
# ------------------------------------------------------------------
# Author : Daniel Balsam
# Title  : Deletes Connection Monitors from Network Watcher
# Description : See SNOW Ticket # RITM0781812
# ------------------------------------------------------------------
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0103-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0103-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0103-2-qa-hpchn-nodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0103-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0106-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0106-2-qa-hpchn-nodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0106-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0114-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0114-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0114-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0122-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0122-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0122-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0122-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0124-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0124-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0124-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0106-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0124-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0127-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0127-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0127-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0127-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0133-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0133-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0133-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0133-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0134-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0134-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0134-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0134-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0135-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0135-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0135-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0136-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0136-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0136-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0136-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0137-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0137-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0137-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0137-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0138-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0138-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0138-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0138-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0139-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0139-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0139-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0139-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0140-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0140-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0140-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0140-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0141-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0141-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0141-2-qa-hpchn-nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0141-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0142-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0142-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0142-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0142-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0143-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0143-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0143-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0143-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0144-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0144-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0144-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0144-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0145-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0145-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0145-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0145-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0146-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0146-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0146-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0146-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0147-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0147-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0147-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0147-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0148-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0148-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0148-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0148-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0149-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0149-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0149-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0149-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0150-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0150-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0150-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0150-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0151-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0151-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0151-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0151-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0152-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0152-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0152-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0152-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0153-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0153-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0153-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0153-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0154-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0154-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0154-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0154-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0155-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0155-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0155-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0155-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0156-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0156-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0156-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0156-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0157-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0157-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0157-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0157-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0158-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0158-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0161-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0158-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0161-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0158-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0161-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0159-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0161-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0159-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0162-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0159-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0162-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0159-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0162-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0160-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0162-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0160-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0163-2-qa-xvabroker-url
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0160-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0163-2-qa-xvasql-2ndip
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0160-2-qa-hpchn-sesmgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0163-2-qa-hpchn--nameodemgr
az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0163-2-qa-hpchn-sesmgr
#az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0164-2-qa-xvabroker-url
#az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0164-2-qa-xvasql-2ndip
#az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0164-2-qa-hpchn--nameodemgr
#az network watcher connection-monitor delete -l northcentralus --name 7264-iazncqvhpc0164-2-qa-hpchn-sesmgr
